apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-sales
  template:
    metadata:
      labels:
        app: app-sales
    spec:
      containers:
        - name: sales-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_USER
            - name: SPRING_RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  key: RABBIT_MQ_HOST
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  key: MQ_USER
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MQ_USER