apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-deployment
spec:
  selector:
    matchLabels:
      version: stable
  template:
    metadata:
      labels:
        version: stable
    spec:
      containers:
        - name: book-service
          image: localhost:5000/book-service:latest
          resources:
            requests:
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secrets-prod
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets-prod