apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-deployment
spec:
  template:
    spec:
      containers:
        - name: book-service-stable
          image: localhost:5000/book-service:latest
          resources:
            requests:
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-books-svc.postgres.svc.cluster.local:5432/db_books
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secrets-prod
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets-prod
                  key: POSTGRES_PASSWORD