postgres:
  username: cG9zdGdyZXM=
  password: cG9zdGdyZXM=
mq:
  username: dXNlcg==
  password: dXNlcg==

virtualService:
  hosts:
    - "*"   # todo add real host ex. 'stage.licensepro.com'
  gateways:
    - "stage-gateway"

canaryTrafficPercentage: 0

app_books:
  stable:
    replicas: 1
    image:
      repository: localhost:5000
      name: book-service
      tag: stage
  canary:
    enabled: false
  virtualService:
    hosts:
      - "*"   # todo add real host ex. 'stage.licensepro.com'
    gateways:
      - "stage-gateway"
  destinationRule:
    subsets:
      - name: stable
        labels:
          version: stable

app-library:
  stable:
    replicas: 1
    image:
      repository: localhost:5000
      name: library-service
      tag: stage

app-sales:
  stable:
    replicas: 1
    image:
      repository: localhost:5000
      name: sales-service
      tag: stage

app-search:
  stable:
    replicas: 1
    image:
      repository: localhost:5000
      name: search-service
      tag: stage