postgres:
  username: cG9zdGdyZXM=
  password: cG9zdGdyZXM=
mq:
  username: dXNlcg==
  password: dXNlcg==

virtualService:
  hosts:
    - "*"   # todo add real host ex. 'stage.licensepro.com'
  gateways:
    - "stage-gateway"

canaryTrafficPercentage: 20

app_books:
  stable:
    replicas: 1
    image:
      repository: localhost:5000
      name: books-image
      tag: latest
  canary:
    enabled: true
    replicas: 1
    image:
      name: book-service
      tag: canary
  virtualService:
    hosts:
      - "*"   # todo add real host ex. 'licensepro.com'
    gateways:
      - "prod-gateway"
  destinationRule:
    subsets:
      - name: stable
        labels:
          version: stable
      - name: canary
        labels:
          version: canary

app-library:
  stable:
    replicas: 1
    image:
      repository: localhost:5000
      name: library-service
      tag: latest

app-sales:
  stable:
    replicas: 1
    image:
      repository: localhost:5000
      name: sales-service
      tag: latest

app-search:
  stable:
    replicas: 1
    image:
      repository: localhost:5000
      name: search-service
      tag: latest