apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-deployment
spec:
  template:
    spec:
      containers:
        - name: sales-service
          image: localhost:5000/sales-service:stage
          imagePullPolicy: Always
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secrets-stage
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets-stage
            - name: SPRING_RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: sales-config
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secrets-stage
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets-stage
            - name: VALUE_FROM_MANIFEST
              value: test