apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Chart.Name}}-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.stable.replicas }}
  selector:
    matchLabels:
      app: {{.Chart.Name}}
  template:
    metadata:
      labels:
        app: {{.Chart.Name}}
    spec:
      containers:
        - name: {{.Chart.Name}}-service
          image: "{{ .Values.stable.image.repository }}/{{ .Values.stable.image.name }}:{{ .Values.stable.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-sales-svc.postgres.svc.cluster.local:5432/db_sales"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: service-secret
                  key: databaseUsername
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: service-secret
                  key: databaseUsername
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq-svc.rabbitmq.svc.cluster.local"
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: service-secret
                  key: mqUsername
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: service-secret
                  key: mqPassword
            - name: VALUE_FROM_MANIFEST
              value: "my super value"