apiVersion: v1
kind: Secret
metadata:
  name: service-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data: # base64
  POSTGRES_USER: {{ .Values.postgres.password }}
  POSTGRES_PASSWORD: {{ .Values.postgres.username}}
  MQ_USER: {{.Values.mq.username}}
  MQ_PASSWORD: {{.Values.mq.password}}