apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-service
  namespace: ms-stage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sales-service
  template:
    metadata:
      labels:
        app: sales-service
    spec:
      containers:
        - name: sales-service
          image: localhost:5000/sales-service:stage
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: sales-config
                  key: DATABASE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: POSTGRES_USER
            - name: SPRING_RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: sales-config
                  key: RABBIT_MQ_HOST
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mq-secret
                  key: MQ_USER
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mq-secret
                  key: MQ_USER
            - name: VALUE_FROM_MANIFEST
              value: "My Super Value"
            #- name: SPRING_APPLICATION_JSON
            #  value: '{ "value.from.manifest": "new value" }'
          resources:
            requests:
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"