apiVersion: v1
kind: Service
metadata:
  name: sales-service
  namespace: ms-stage
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30082
  selector:
    app: sales-service