apiVersion: v1
kind: Service
metadata:
  name: library-service
  namespace: ms-stage
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30081
  selector:
    app: library-service