apiVersion: v1
kind: Service
metadata:
  name: search-service
  namespace: ms-stage
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30083
  selector:
    app: search-service