apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-stable
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    version: stable
spec:
  replicas: {{ .Values.stable.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      version: stable
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        version: stable
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.stable.image.repository }}/{{ .Values.stable.image.name }}:{{ .Values.stable.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

{{- if and .Values.canary .Values.canary.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-canary
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    version: canary
spec:
  replicas: {{ .Values.canary.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      version: canary
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        version: canary
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.stable.image.repository }}/{{ .Values.canary.image.name }}:{{ .Values.canary.image.tag }}"
          ports:
            - containerPort: 8080
{{- end }}
