apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: app-books-{{ .Release.Namespace }}-destination-rule
  namespace: {{ .Release.Namespace }}
spec:
  host: book-service.{{ .Release.Namespace }}.svc.cluster.local
  subsets:
  {{- range .Values.destinationRule.subsets }}
    - name: {{ .name }}
      labels: {{ toYaml .labels | nindent 8 }}
  {{- end }}
