apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Namespace }}-virtual-service
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  {{- toYaml .Values.virtualService.hosts | nindent 2 }}
  gateways:
  {{- toYaml .Values.virtualService.gateways | nindent 2 }}
  http:
    - route:
        - destination:
            host: book-service.{{ .Release.Namespace }}.svc.cluster.local
            subset: stable
          weight: {{ if .Values.canary.enabled }}{{ sub 100 .Values.canary.trafficPercentage }}{{ else }}100{{ end }}
        {{- if .Values.canary.enabled }}
        - destination:
            host: book-service.{{ .Release.Namespace }}.svc.cluster.local
            subset: canary
          weight: {{ .Values.canary.trafficPercentage }}
        {{- end }}
