apiVersion: v1
kind: Secret
metadata:
  name: service-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data: # base64
  databaseUsername: "cG9zdGdyZXM=" #postgres
  databasePassword: "cG9zdGdyZXM="
  mqUsername: "dXNlcg==" #user
  mqPassword: "dXNlcg=="