apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
  namespace: ms-stage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
        - name: search-service
          image: localhost:5000/search-service:stage
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"