stable:
  replicas: 1
  image:
    repository: localhost:6000
    name: books-image
    tag: stage

canary:
  enabled: false

destinationRule:
  subsets:
    - name: stable
      labels:
        version: stable

secrets:
  databaseUsername: cG9zdGdyZXM=
  databasePassword: cG9zdGdyZXM=